services:
  db:
    image: postgres:16-alpine
    container_name: app_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app_web
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     # pass server env to Next.js runtime
  #     DATABASE_URL: ${DATABASE_URL}
  #     REDIS_URL: ${REDIS_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #     ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
  #     REFRESH_TOKEN_TTL_SECONDS: ${REFRESH_TOKEN_TTL_SECONDS}
  #     REFRESH_COOKIE_NAME: ${REFRESH_COOKIE_NAME}
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"

volumes:
  pgdata:
